#' Create age-length key from combined acoustic survey and bottom trawl data.
#'
#' @param year Numeric vector representing the year of data collection.
#' @param lake Numeric vector with the USGS-GLSC RVCAT numeric code for the
#' Great Lake in which data were collected.
#' @param target Numeric vector of the numeric code for the RVCAT target associated
#' with the desired data. Used to help limit the data to a desired study or survey.
#' @param user Character vector providing the username used to connect to
#' the database.
#' @param password Character vector providing the password used to connect to
#' the database.
#' @param schma Character vector providing the schema used to connect to
#' the database. Default is "RVCAT".
#' @param outdir Character vector representing the parent directory in which the
#' output directory where data should be saved is located. The values for lakec and
#' year are pasted together with this directory name to provide the output location
#' for files generated by the function. This folder must exist already.
#' @param species Numeric vector of the RVCAT species codes for the species
#' the user wishes to study.
#'
#' @return
#' An age-length key formatted for EchoNet2Fish.
#'
#' @import fishmethods ROracle dplyr
#' @export
#' @details
#' This function is primarily a wrapper for fishmethods::alk() (Nelson 2018) combined
#' with an Oracle database query that is used to obtain the data.
#'
#' @references
#' Gary A. Nelson (2018). fishmethods: Fishery Science Methods and Models. R package version 1.11-0. https://CRAN.R-project.org/package=fishmethods
#'
BuildCombinedAgeKey <- function(year = NULL,
                                lake = NULL,
                                target = c(1, 209, 210, 223),
                                user = username,
                                password = password,
                                dbname = dbname,
                                schma = "RVCAT",
                                outdir = NULL,
                                species = c(106)) {
  outdir <- choose.dir()
  drv <- dbDriver('Oracle')
  conn <- dbConnect(
    drv = drv,
    dbname = dbname,
    user = username,
    password = password
  )
  # Create local "information" about op table structure that can
  # be used in a query later
  #
  # Now op is a database object. The command above connects to the database
  # and downloads a bare minimum of information on fields, data types, etc.
  # enough to allow manipulation of the object without physical download
  # of the data
  # (https://towardsdatascience.com/how-to-write-tidy-sql-queries-in-r-d6d6b2a3e17)
  opdata <- dplyr::tbl(conn,
                       dbplyr::in_schema("RVCAT", "OP"))

  # Create local "information" about op_target table structure that can
  # be used in a query later
  targetdata <- dplyr::tbl(conn,
                           dbplyr::in_schema("RVCAT", "OP_TARGET"))

  # Create tr_fish data object
  trfishdata <- dplyr::tbl(conn,
                           dbplyr::in_schema("RVCAT", "TR_FISH"))
  op <-
    filter(opdata, YEAR %in% year &
             LAKE %in% lake & SAMPLE_TYPE == 1) %>%
    left_join(targetdata, by = "OP_ID") %>% filter(TARGET %in% target)  %>%
    dplyr::collect()
  # Create list of OP_ID to use to subset the tr_op, tr_catch, and tr_lf
  opid <- op$OP_ID

  tr_fish <- filter(trfishdata, OP_ID %in% opid & !(is.na(AGE)) &
                      SPECIES == species) %>%
    dplyr::collect()

  mykey <-
    alk(
      age = tr_fish$AGE,
      size = tr_fish$LENGTH,
      binsize = 10,
      type = 2
    )

  nam <- names(mykey)
  ages <- substr((tail(nam, -2)), 2, 2)
  agepref <- rep("Age", length.out = length(ages))
  agelenkey <- mykey %>% select(-nl)
  agenames <- paste0(agepref, ages)
  names(agelenkey) <- c("mmgroup", agenames)

  #create and fill mmgroups < smallest and largest
  stretch <- data.frame(mmgroup = seq(5, 225, 10))
  stretched.key <-
    merge(stretch, agelenkey, by = "mmgroup", all.x = TRUE)
  stretched.key$Age0[is.na(stretched.key$Age0) &
                       stretched.key$mmgroup < 100] <- 1
  stretched.key$Age0[is.na(stretched.key$Age0) &
                       stretched.key$mmgroup < 150] <- 0
  sel <- grepl("Age", names(stretched.key))
  stretched.key[sel] <-
    lapply(stretched.key[sel], function(x)
      replace(x, x %in% NA, 0))
  write.csv(
    stretched.key,
    paste0(
      outdir,
      "/species_",
      species,
      "_",
      year,
      "_age_length_key.csv",
      row.names = FALSE
    )
  )

}
