#' Execute query of multiple Oracle trawl tables for use by EchoNet2Fish functions
#' @param year Numeric vector indicating the desired collection year(s).
#' @param lake Numeric vector indicating the desired collection lake(s).
#' @param lakec Character vector representing an abbreviation for the lake name.
#' This value is used to direct output files to the correct subfolder of the
#' folder in which the EchoNet2Fish reference file is located. For example, if
#' the path to this folder is C:/Documents/Acoustics/EchoNet2Fish and data are
#' from the year 2018 and lake with abbreviation (lakec) "MI", the output will
#' be written to the folder C:/Documents/Acoustics/EchoNet2Fish/MI2018.
#' @param target Numeric vector indicating the desired collection target(s).
#' @param species Numeric vector of RVCAT species codes for which you wish to
#' query.
#' @param user Character vector providing the username used to connect to
#' the database.
#' @param password Character vector providing the password used to connect to
#' the database.
#' @param schma Character vector providing the schema used to connect to
#' the database. Default is "RVCAT".
#' @param outdir Character vector representing the parent directory in which the
#' output directory where data should be saved is located. The values for lakec and
#' year are pasted together with this directory name to provide the output location
#' for files generated by the function. This folder must exist already.
#' @param descr Character vector to include in the output file names to help identify
#' the data for later use. Default is "Acoustic".
#' in only a subset of fields being returned. The subset includes
#' @return
#'   Six different data frames are saved as objects in an Rdata file and are written to csv
#'   files in \code{outdir}:
#'   \itemize{
#'     \item \code{op} = Data from the RVCAT.OP table for the desired selection.
#'     \item \code{tr_op} = Data from the RVCAT.TR_OP table matching the operations
#'     in the op data.
#'     \item \code{tr_catch} = Data from the RVCAT.TR_CATCH table matching the
#'     operations in the op data
#'     \item \code{tr_lf} = Data from the RVCAT.TR_LF table matching the operations
#'     in the op data.
#'     \item \code{tr_l} = Data from the RVCAT.TR_L table matching the operations
#'     in the op data.
#'     \item \code{tr_fish} = Data from the RVCAT.TR_FISH table matching the operations
#'     in the op data.
#'     }
#' @import dplyr rtf graphics utils tidyr
#' @export

#' @details
#' This function queries the RVCAT database to obtain trawl data desired by the user.
#' It currently allows the user to determine if certain field names should be renamed
#' to match the requirements of Echonet2Fish functions.

trawl_query <- function(year = c(2019), lake = c(2,3),
                        lakec = c("MI", "HU"),
                        target = c(209, 210, 252),
                        species = c(106, 109, 202, 203, 204, 504),
                         user = username,
                        password = password, dbname = dbname, schma = "RVCAT",
                        descr = "LW acoustic survey",  outdir = NULL) {

  drv <- dbDriver("Oracle")
  conn <- dbConnect(drv = drv, dbname = dbname, user = username,
                    password = password)
  opdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                               "OP"))
  targetdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                   "OP_TARGET"))
  trcatchdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                    "TR_CATCH"))
  tropdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                 "TR_OP"))
  trlfdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                 "TR_LF"))
  trldata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                "TR_L"))
  trfishdata <- dplyr::tbl(conn, dbplyr::in_schema("RVCAT",
                                                   "TR_FISH"))
  op <- filter(opdata, YEAR %in% year & LAKE %in% lake & SAMPLE_TYPE ==
                 1 & VESSEL != 41) %>% left_join(targetdata, by = "OP_ID") %>%
    filter(TARGET %in% target) %>%
    mutate(Latitude = (BEG_LATITUDE_DD +
                         END_LATITUDE_DD)/2, Longitude = (BEG_LONGITUDE_DD + END_LONGITUDE_DD)/2) %>%
    select(OP_ID, YEAR, VESSEL, SERIAL, SAMPLE_TYPE, LAKE,
           PORT, CRUISE, OP_DATE, TIME, LATITUDE, LONGITUDE,
           BEG_DEPTH, END_DEPTH, END_LATITUDE, END_LONGITUDE,
           DISTANCE, STATION_DEPTH, BEG_LATITUDE_DD, END_LATITUDE_DD,
           BEG_LONGITUDE_DD, END_LONGITUDE_DD, TRANSECT, Latitude,
           Longitude) %>% dplyr::collect()
  exclude <- c("gb1", "gb2",
               "gb3", "gb4", "gb5", "gb6",
               "gb7", "gb8", "gb9", "gb10", "gb11", "gb12", "gb13",
               "gb99", "GTB",  "gt1",
               "gt2", "gt3", "gt3", "gt4", "gt5", "gt6", "gt7",
               "gt8", "gtb1",
               "gtb2", "gtb3", "gtb4", "gtb5",
               "gtb6",
               "GB2",
               "GB3",
               "GB3",
               "GB4",
               "GB4",
               "GB5",
               "GB5",
               "GB7",
               "GB7",
               "GB6"
  )
  if (lake == 2) {

    op <- op %>% filter(!(TRANSECT %in% exclude))
  }
  opid <- op$OP_ID
  tr_op <- filter(tropdata, OP_ID %in% opid ) %>% select(OP_ID,
                                                        SET_TIME, TOW_TIME, FISHING_TEMP, FISHING_DEPTH) %>%
    dplyr::collect()
  optrop <- merge(op, tr_op, by = "OP_ID")
  tr_catch <- filter(trcatchdata, OP_ID %in% opid) %>% filter(SPECIES %in%
                                                                species) %>% dplyr::collect()
  tr_lf <- filter(trlfdata, OP_ID %in% opid) %>% filter(SPECIES %in%
                                                          species) %>% dplyr::collect()
  tr_l <- filter(trldata, OP_ID %in% opid) %>% filter(SPECIES %in%
                                                        species) %>% dplyr::collect()
  tr_fish <- filter(trfishdata, OP_ID %in% opid) %>% filter(SPECIES %in%
                                                              species) %>% dplyr::collect()
  save2csv <- c("op", "tr_op", "optrop",
                "tr_catch", "tr_lf", "tr_l", "tr_fish")
  newrdat <- paste0("L", lake, " Y", year, " ",
                    descr)
  lakeyr <- ifelse(lake == 2, paste0("MI", year), paste0("HU",
                                                         year))
  outfiles <- paste0(outdir, "/", lakeyr, "/",
                     "L_", lake, "_Y_", year, "_", descr,
                     "_", save2csv, ".csv")
  invisible(lapply(seq(save2csv), function(i) write.csv(eval(parse(text = save2csv[i]),
  ), outfiles[i], row.names = F)))

}

